[package]
name = "tariskills-counter"
version = "0.1.0"
edition = "2024"
publish = false
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
tari_template_lib = "=0.32.0"
[dev-dependencies]
tari_template_test_tooling = "=0.41.0"
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true
strip = true
[profile.dev.package.wasmer]
opt-level = 2
[profile.dev.package.wasmer-compiler-cranelift]
opt-level = 2
